### ISSUE TITLE
Issues with Werkzeug Package Version

### ISSUE THREAD

**Issue by ASG-Dev1** [Azure/gpt-rag-frontend#13]
Hi,

I encountered some issues when using the Werkzeug package with the current version in the repository. To resolve the problem, I had to downgrade to Werkzeug version 2.2.2. It might be helpful to specify this version in the requirements or address the compatibility issues with the latest version.

Thanks!

![Screenshot 2023-10-02 at 8 46 40 AM](https://github.com/Azure/gpt-rag-frontend/assets/112154154/ce6a4b17-ebb5-4a46-a08d-36268b31ceee)

**Comment by placerda** [comment]
Thanks @ASG-Dev1 fixed in c5a5a0f8f169071c7a2bd109a932fb2f57f672a3.
